version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/packages/databricks-sdk-js"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "@databricks/*"
  - package-ecosystem: "npm"
    directory: "/packages/databricks-vscode"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "@databricks/*"
  - package-ecosystem: "npm"
    directory: "/packages/databricks-vscode-types"
    ignore:
      - dependency-name: "@databricks/*"
    schedule:
      interval: "daily"
